export const OBTENER_PERSONAS = 'OBTENER_PERSONAS';
export const OBTENER_REGIONES = 'OBTENER_REGIONES';
export const OBTENER_CIUDADES = 'OBTENER_CIUDADES';
export const OBTENER_COMUNAS = 'OBTENER_COMUNAS';

export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO';
