export const OBTENER_PERSONAS = 'OBTENER_PERSONAS';
export const OBTENER_REGIONES = 'OBTENER_REGIONES';
export const OBTENER_CIUDADES = 'OBTENER_CIUDADES';
export const OBTENER_COMUNAS = 'OBTENER_COMUNAS';
export const CREAR_PERSONA = 'CREAR_PERSONA';

export const OBTENER_UNA_PERSONAS = 'OBTENER_UNA_PERSONAS';
export const ACTUALIZAR_UNA_PERSONA = 'ACTUALIZAR_UNA_PERSONA';
export const ELIMINAR_UNA_PERSONA= 'ELIMINAR_UNA_PERSONA';
